sudo -E su

if [ ! -x "/usr/bin/redis-server" ]; then
  wget http://redis.googlecode.com/files/redis-2.2.13.tar.gz
  tar zxf redis-2.2.13.tar.gz
  cd redis-2.2.13
  make
  mv src/redis-server /usr/bin/redis-server-2.2.13
  mv src/redis-cli /usr/bin/redis-cli-2.2.13
  ln -s /usr/bin/redis-server-2.2.13 /usr/bin/redis-server
  ln -s /usr/bin/redis-cli-2.2.13 /usr/bin/redis-cli
fi

id redis ||
  addgroup redis &&
  adduser --system --no-create-home --ingroup redis --disabled-login redis

mkdir -p /etc/redis
chown root:root /etc/redis
chmod 0755 /etc/redis

mkdir -p /var/lib/redis
chown root:root /var/lib/redis
chmod 0755 /var/lib/redis

touch /var/log/redis.log
chown redis:redis /var/lib/redis

cat <<EOS > /etc/init.d/redis
#! /bin/sh

### BEGIN INIT INFO
# Provides:		redis-server
# Required-Start:	\$syslog
# Required-Stop:	\$syslog
# Should-Start:		\$local_fs
# Should-Stop:		\$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	redis-server - Persistent key-value db
# Description:		redis-server - Persistent key-value db
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/redis-server
DAEMON_ARGS=/etc/redis/redis.conf
NAME=redis-server
DESC=redis-server
PIDFILE=/var/run/redis.pid

test -x \$DAEMON || exit 0
test -x \$DAEMONBOOTSTRAP || exit 0

set -e

case "\$1" in
  start)
	echo -n "Starting \$DESC: "
	touch \$PIDFILE
	chown redis:redis \$PIDFILE
	if start-stop-daemon --start --quiet --umask 007 --pidfile \$PIDFILE --chuid redis:redis --exec \$DAEMON -- \$DAEMON_ARGS
	then
		echo "\$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping \$DESC: "
	if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile \$PIDFILE --exec \$DAEMON
	then
		echo "\$NAME."
	else
		echo "failed"
	fi
	rm -f \$PIDFILE
	;;

  restart|force-reload)
	\${0} stop
	\${0} start
	;;
  *)
	echo "Usage: /etc/init.d/\$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
EOS
chown root:root /etc/init.d/redis
chmod 0755 /etc/init.d/redis

cat <<EOS > /etc/redis/redis.conf
#
# Generated by tele
#
daemonize yes
pidfile /var/run/redis.pid
port 6379
bind 0.0.0.0
timeout 300
save 900 1
save 300 10
save 60 10000
dbfilename dump.rdb
dir /var/lib/redis
loglevel notice
logfile /var/log/redis.log
databases 16
glueoutputbuf yes
EOS
chown root:root /etc/redis/redis.conf
chmod 0644 /etc/redis/redis.conf

/etc/init.d/redis start
